name: Daily Commit

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "Apoorv Khobragade"
          git config user.email "180470498+ApoorvBytes@users.noreply.github.com"

      - name: Publish one file
        run: |
          FILE=$(ls source | head -n 1)

          if [ -z "$FILE" ]; then
            echo "No files left"
            exit 0
          fi

          cp source/$FILE daily/$FILE
          rm source/$FILE

          git add .
          git commit -m "Daily Practical: $FILE"
          git push
